/**
 * M2 · RuntimeCredentialProvider（RED）
 *
 * 架构 §8：Provider 从 0600 私有文件读取 bootstrap 结果，到期前 5 分钟重铸；
 * 刷新失败时保留仍有效的旧 token 并指数退避；token/session 不进 stdout、health 或普通日志。
 * 任务书 §4.2/§4.4/§4.5：显式 `datastore.read/write`、401 只刷新一次、剩 5 分钟/刚过期/时钟偏移。
 *
 * 输入是**真 CLI 的产物**，不是我们自己定的 JSON：
 * `waku agent bootstrap --write-runtime-js <path>` 写出的是一段 JS
 *   `window.__POLYVERSE_RUNTIME__ = Object.assign({}, window.__POLYVERSE_RUNTIME__ || {}, {…})`
 * （`cli/waku/waku_cli.mjs::buildRuntimeBootstrapScript`，`JSON.stringify(payload,null,2)` 且把
 * `</` 转义成 `<\/`），文件用 `writePrivateFile` 落 0600。payload 键：
 * environment / apiBaseUrl / runtimeToken / sessionId / projectId / contentId / origin /
 * capabilities / expiresAt。
 *
 * 所以 provider 不能 `JSON.parse(整个文件)`，也**不能 eval 这段 JS**——它是磁盘上的可执行文本，
 * 拿它当代码跑等于给任何能写这个文件的人一次 RCE。本文件用「文件里多塞一句 throw」证明没执行。
 */
import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { randomBytes } from 'node:crypto';

import { captureAsync, lazyModule } from './fake-waku.js';

// ---------------------------------------------------------------------------
// 测试侧契约
// ---------------------------------------------------------------------------

type RuntimeCredentials = {
  token: string;
  sessionId: string;
  apiBaseUrl: string;
  origin: string;
  /** epoch ms（文件里可能是 ISO 串，归一在 provider 里做）。 */
  expiresAt: number;
  capabilities: readonly string[];
};

type CredentialHealth = {
  ok: boolean;
  /** ready=正常；stale=刷新失败但旧 token 仍有效；degraded=已过期且刷不出来。 */
  state: 'ready' | 'stale' | 'degraded';
  expiresInSec: number;
  refreshFailures: number;
  lastRefreshError?: string;
};

type RuntimeCredentialProviderApi = {
  current(): Promise<RuntimeCredentials>;
  refresh(): Promise<void>;
  health(): CredentialHealth;
};

type CredentialProviderModule = {
  createRuntimeCredentialProvider(options: {
    runtimeJsPath: string;
    /** 重新执行 bootstrap（真实实现是 spawn waku CLI；测试注入函数）。 */
    mint: () => Promise<void>;
    now: () => number;
    refreshSkewMs?: number;
    requiredCapabilities?: readonly string[];
    backoff?: { baseMs: number; maxMs: number };
  }): RuntimeCredentialProviderApi;
  RUNTIME_TOKEN_REFRESH_SKEW_MS: number;
  REQUIRED_RUNTIME_CAPABILITIES: readonly string[];
};

type CredentialError = Error & { code: string };

const loadProvider = lazyModule<CredentialProviderModule>('../../gateway/channels/waku/credential-provider.js');

function asCredentialError(e: unknown): CredentialError {
  return e as CredentialError;
}

// ---------------------------------------------------------------------------
// Fixture：按 CLI 的真实写法造文件
// ---------------------------------------------------------------------------

const T0 = 1_760_000_000_000;
const HOUR = 60 * 60 * 1000;
const API_BASE = 'https://aicap.example.test/api';
const ORIGIN = 'http://127.0.0.1:47311';

type BootstrapPayload = {
  environment: string;
  apiBaseUrl: string;
  runtimeToken: string;
  sessionId: string;
  projectId: string | null;
  contentId: string | null;
  origin: string;
  capabilities: string[];
  expiresAt: string | number;
};

function payloadFor(overrides: Partial<BootstrapPayload> = {}): BootstrapPayload {
  return {
    environment: 'web',
    apiBaseUrl: API_BASE,
    runtimeToken: `rt_${randomBytes(24).toString('base64url')}`,
    sessionId: `rts_${randomBytes(8).toString('hex')}`,
    projectId: 'prj_dogfood',
    contentId: null,
    origin: ORIGIN,
    capabilities: ['datastore.read', 'datastore.write'],
    expiresAt: new Date(T0 + HOUR).toISOString(),
    ...overrides,
  };
}

/** 逐字复刻 `buildRuntimeBootstrapScript` + `writePrivateFile`。 */
function writeRuntimeJs(target: string, payload: BootstrapPayload, options: { mode?: number; extra?: string } = {}): void {
  const json = JSON.stringify(payload, null, 2).replace(/<\//g, '<\\/');
  const body =
    `// Generated by waku agent bootstrap. Do not commit this file.\n` +
    `(function(window) {\n` +
    `  window.__POLYVERSE_RUNTIME__ = Object.assign({}, window.__POLYVERSE_RUNTIME__ || {}, ${json});\n` +
    `})(typeof window !== "undefined" ? window : globalThis);\n` +
    (options.extra ?? '');
  const mode = options.mode ?? 0o600;
  fs.writeFileSync(target, body, { encoding: 'utf8', mode });
  fs.chmodSync(target, mode);
}

let dir: string;
let runtimeJsPath: string;
let clock: number;
let mintCalls = 0;

beforeEach(() => {
  dir = fs.mkdtempSync(path.join(os.tmpdir(), 'waku-cred-'));
  runtimeJsPath = path.join(dir, 'runtime.js');
  clock = T0;
  mintCalls = 0;
});

afterEach(() => {
  fs.rmSync(dir, { recursive: true, force: true });
});

async function makeProvider(options: {
  mint?: () => Promise<void>;
  refreshSkewMs?: number;
  requiredCapabilities?: readonly string[];
  backoff?: { baseMs: number; maxMs: number };
} = {}): Promise<RuntimeCredentialProviderApi> {
  const mod = await loadProvider();
  return mod.createRuntimeCredentialProvider({
    runtimeJsPath,
    now: () => clock,
    mint:
      options.mint ??
      (() => {
        mintCalls += 1;
        writeRuntimeJs(runtimeJsPath, payloadFor({ expiresAt: new Date(clock + HOUR).toISOString() }));
        return Promise.resolve();
      }),
    refreshSkewMs: options.refreshSkewMs,
    requiredCapabilities: options.requiredCapabilities,
    backoff: options.backoff,
  });
}

// ---------------------------------------------------------------------------

describe('M2 · RuntimeCredentialProvider 解析 bootstrap 产物', () => {
  it('读真 CLI 格式的 runtime.js，交出 token/sessionId/apiBaseUrl/origin/expiresAt/capabilities', async () => {
    const payload = payloadFor();
    writeRuntimeJs(runtimeJsPath, payload);

    const provider = await makeProvider();
    const cred = await provider.current();

    expect(cred.token).toBe(payload.runtimeToken);
    expect(cred.sessionId).toBe(payload.sessionId);
    expect(cred.apiBaseUrl).toBe(API_BASE);
    expect(cred.origin).toBe(ORIGIN);
    expect(cred.expiresAt).toBe(T0 + HOUR);
    expect([...cred.capabilities].sort()).toEqual(['datastore.read', 'datastore.write']);
  });

  it('expiresAt 是 epoch 毫秒数时同样归一（后端字段形态换了不该炸）', async () => {
    writeRuntimeJs(runtimeJsPath, payloadFor({ expiresAt: T0 + HOUR }));
    const provider = await makeProvider();
    expect((await provider.current()).expiresAt).toBe(T0 + HOUR);
  });

  it('不执行文件里的 JS：文件尾部多一句 throw 也照样解析成功', async () => {
    writeRuntimeJs(runtimeJsPath, payloadFor(), { extra: `throw new Error("runtime.js must never be executed");\n` });
    const provider = await makeProvider();
    await expect(provider.current()).resolves.toMatchObject({ apiBaseUrl: API_BASE });
  });

  it('文件缺失 → waku_credential_missing，且提示怎么补（不吞成空凭证）', async () => {
    const provider = await makeProvider();
    const err = asCredentialError(await captureAsync(() => provider.current()));

    expect(err.code).toBe('waku_credential_missing');
    expect(err.message).toContain('bootstrap');
  });

  it('文件内容不是 bootstrap 产物（半截/垃圾）→ waku_credential_unreadable', async () => {
    fs.writeFileSync(runtimeJsPath, '// Generated by waku agent bootstrap.\n(function(window) {\n  window.__POLY', {
      mode: 0o600,
    });
    const provider = await makeProvider();
    const err = asCredentialError(await captureAsync(() => provider.current()));
    expect(err.code).toBe('waku_credential_unreadable');
  });

  it('权限不是 0600 → fail closed（token 已经被别的用户看过了，不能当没事）', async () => {
    writeRuntimeJs(runtimeJsPath, payloadFor(), { mode: 0o644 });
    const provider = await makeProvider();
    const err = asCredentialError(await captureAsync(() => provider.current()));

    expect(err.code).toBe('waku_credential_insecure_file');
    expect(err.message).not.toContain('rt_');
  });

  it('capabilities 缺 datastore.write → fail closed，并指出要补哪个 flag', async () => {
    writeRuntimeJs(runtimeJsPath, payloadFor({ capabilities: ['datastore.read'] }));
    const provider = await makeProvider();
    const err = asCredentialError(await captureAsync(() => provider.current()));

    expect(err.code).toBe('waku_credential_capability_missing');
    expect(err.message).toContain('datastore.write');
    expect(err.message).toContain('--runtime-capabilities');
  });

  it('默认必需 capability 就是 datastore.read + datastore.write（架构 §8 铸权要求）', async () => {
    const mod = await loadProvider();
    expect([...mod.REQUIRED_RUNTIME_CAPABILITIES].sort()).toEqual(['datastore.read', 'datastore.write']);
    expect(mod.RUNTIME_TOKEN_REFRESH_SKEW_MS).toBe(5 * 60 * 1000);
  });
});

describe('M2 · RuntimeCredentialProvider 到期刷新', () => {
  it('剩余 > 5 分钟不刷新（不白烧 CLI 与后端 session）', async () => {
    writeRuntimeJs(runtimeJsPath, payloadFor());
    const provider = await makeProvider();

    clock = T0 + HOUR - 6 * 60 * 1000;
    await provider.current();
    expect(mintCalls).toBe(0);
    expect(provider.health().state).toBe('ready');
  });

  it('进入到期前 5 分钟窗口时重铸，新 sessionId 立即生效', async () => {
    writeRuntimeJs(runtimeJsPath, payloadFor());
    const provider = await makeProvider();
    const before = await provider.current();

    clock = T0 + HOUR - 5 * 60 * 1000;
    const after = await provider.current();

    expect(mintCalls).toBe(1);
    expect(after.sessionId).not.toBe(before.sessionId);
    expect(after.token).not.toBe(before.token);
    expect(after.expiresAt).toBe(clock + HOUR);
  });

  it('并发 current() 只触发一次重铸（single-flight，防刷新风暴）', async () => {
    writeRuntimeJs(runtimeJsPath, payloadFor());
    const provider = await makeProvider();
    clock = T0 + HOUR - 60_000;

    const results = await Promise.all([provider.current(), provider.current(), provider.current()]);
    expect(mintCalls).toBe(1);
    expect(new Set(results.map((r) => r.token)).size).toBe(1);
  });

  it('服务端时钟偏移导致刚铸就已过期 → 立刻重铸一次而不是直接不可用', async () => {
    writeRuntimeJs(runtimeJsPath, payloadFor({ expiresAt: new Date(T0 - 1000).toISOString() }));
    const provider = await makeProvider();

    const cred = await provider.current();
    expect(mintCalls).toBe(1);
    expect(cred.expiresAt).toBe(T0 + HOUR);
  });
});

describe('M2 · RuntimeCredentialProvider 刷新失败与退避', () => {
  function failingMint(): () => Promise<void> {
    return () => {
      mintCalls += 1;
      return Promise.reject(new Error('waku agent bootstrap exited with code 1'));
    };
  }

  it('刷新失败但旧 token 仍有效 → 继续用旧 token，state=stale', async () => {
    const payload = payloadFor();
    writeRuntimeJs(runtimeJsPath, payload);
    const provider = await makeProvider({ mint: failingMint() });

    clock = T0 + HOUR - 60_000;
    const cred = await provider.current();

    expect(cred.token).toBe(payload.runtimeToken);
    expect(mintCalls).toBe(1);
    const health = provider.health();
    expect(health.state).toBe('stale');
    expect(health.ok).toBe(true);
    expect(health.refreshFailures).toBe(1);
  });

  it('指数退避：退避未到期不再重铸，到期后才允许下一次（不循环刷）', async () => {
    writeRuntimeJs(runtimeJsPath, payloadFor());
    const provider = await makeProvider({ mint: failingMint(), backoff: { baseMs: 1000, maxMs: 60_000 } });

    clock = T0 + HOUR - 60_000;
    await provider.current();
    expect(mintCalls).toBe(1);

    clock += 500;
    await provider.current();
    expect(mintCalls).toBe(1);

    clock += 500; // 距上次失败 1000ms
    await provider.current();
    expect(mintCalls).toBe(2);

    clock += 1500; // 第二次失败后要等 2000ms
    await provider.current();
    expect(mintCalls).toBe(2);

    clock += 500;
    await provider.current();
    expect(mintCalls).toBe(3);
  });

  it('token 真过期且仍刷不出来 → current() 拒绝，state=degraded', async () => {
    writeRuntimeJs(runtimeJsPath, payloadFor());
    const provider = await makeProvider({ mint: failingMint(), backoff: { baseMs: 1, maxMs: 10 } });

    clock = T0 + HOUR + 1;
    const err = asCredentialError(await captureAsync(() => provider.current()));

    expect(err.code).toBe('waku_credential_degraded');
    const health = provider.health();
    expect(health.state).toBe('degraded');
    expect(health.ok).toBe(false);
    expect(health.expiresInSec).toBeLessThanOrEqual(0);
  });

  it('显式 refresh() 失败会 reject（调用方看得见），但不会打掉仍可用的旧 token', async () => {
    const payload = payloadFor();
    writeRuntimeJs(runtimeJsPath, payload);
    const provider = await makeProvider({ mint: failingMint() });

    await expect(provider.refresh()).rejects.toThrow();
    expect((await provider.current()).token).toBe(payload.runtimeToken);
  });

  it('刷新成功后退避计数归零，下次失败重新从 base 起算', async () => {
    writeRuntimeJs(runtimeJsPath, payloadFor());
    let shouldFail = true;
    const provider = await makeProvider({
      backoff: { baseMs: 1000, maxMs: 60_000 },
      mint: () => {
        mintCalls += 1;
        if (shouldFail) return Promise.reject(new Error('boom'));
        writeRuntimeJs(runtimeJsPath, payloadFor({ expiresAt: new Date(clock + HOUR).toISOString() }));
        return Promise.resolve();
      },
    });

    clock = T0 + HOUR - 60_000;
    await provider.current();
    expect(provider.health().refreshFailures).toBe(1);

    shouldFail = false;
    clock += 1000;
    await provider.current();
    expect(provider.health().refreshFailures).toBe(0);
    expect(provider.health().state).toBe('ready');
  });

  it('重铸过程中文件被写坏 → 保留旧 token 并记 stale，不把半截文件当新凭证', async () => {
    const payload = payloadFor();
    writeRuntimeJs(runtimeJsPath, payload);
    const provider = await makeProvider({
      mint: () => {
        mintCalls += 1;
        fs.writeFileSync(runtimeJsPath, '(function(window) { window.__POLYVERSE_RUN', { mode: 0o600 });
        return Promise.resolve();
      },
    });

    clock = T0 + HOUR - 60_000;
    const cred = await provider.current();

    expect(cred.token).toBe(payload.runtimeToken);
    expect(provider.health().state).toBe('stale');
  });
});

describe('M2 · RuntimeCredentialProvider 脱敏', () => {
  it('health() 里没有 token / sessionId，只有可公开的到期与状态', async () => {
    const payload = payloadFor();
    writeRuntimeJs(runtimeJsPath, payload);
    const provider = await makeProvider();
    await provider.current();

    const dump = JSON.stringify(provider.health());
    expect(dump).not.toContain(payload.runtimeToken);
    expect(dump).not.toContain(payload.sessionId);
    expect(provider.health().expiresInSec).toBe(HOUR / 1000);
  });

  it('刷新失败的 lastRefreshError 也不许把 token 带出来', async () => {
    const payload = payloadFor();
    writeRuntimeJs(runtimeJsPath, payload);
    const provider = await makeProvider({
      mint: () => {
        mintCalls += 1;
        return Promise.reject(new Error(`bootstrap failed for token ${payload.runtimeToken}`));
      },
    });

    clock = T0 + HOUR - 60_000;
    await provider.current();
    expect(provider.health().lastRefreshError ?? '').not.toContain(payload.runtimeToken);
  });
});
